### ISSUE TITLE
Can't install the mod from the mod browser in-game

### ISSUE THREAD

**Issue by Destro9000** [EB-wilson/Singularity#3]
**Describe the bug**
Error message when trying to install from the mod browser in game (midustry version 7.0 pre alpha 0.135)

**To Reproduce**
1) go to mod browser
2) Click install

**Expected behavior**
Install the mod

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Samsun Galaxy A40
 - Android 11

**Additional context**

**Comment by aarrbba123** [comment]
seems late to post here but it's relevant

It occured to me too (Windows 10).
It seems that the mod link to download from the inbuilt mod browser has been altered,deleted or bugged since the error for me said "not found"...

...I thought that the mod was deleted so I didn't check the repo until now

Here's the screenshot:
![Screenshot (92)](https://user-images.githubusercontent.com/70095196/165490953-17440f4d-b87c-4b74-af67-6296e246848a.png)

Additional info
Platform: Itch.io (pre-alpha 135.2)

**Comment by Gdkdkhkggddg** [comment]
I have the same problem
